// In this file you can specify the trial data for your experiment

// the example trials are defined manually
const training_trials_data = [
    {
      QUD: '',
      bias: 0.5,
      row_number: 5,
      column_number: 12,
      condition: "low",
      question: "Describe these results of <strong>Riverside</strong> so as to make it appear as if there is a <strong>low</strong> success rate without lying.",
      sentence_chunk_1: "In this exam",
      sentence_chunk_2: "of the students got",
      sentence_chunk_3: "of the questions",
      sentence_chunk_4: ".",
      choice_options_1: ["all", "most", "many", "some", "few", "none"],
      choice_options_2: ["all", "most", "many", "some", "few", "none"],
      choice_options_3: ["right", "wrong"]
    },
    {
      QUD: '',
      bias: 0.9,
      row_number: 5,
      column_number: 12,
      condition: "high",
      question: "Describe these results of <strong>Green Valley</strong> so as to make it appear as if there is a <strong>high</strong> success rate without lying.",
      sentence_chunk_1: "In this exam",
      sentence_chunk_2: "of the students got",
      sentence_chunk_3: "of the questions",
      sentence_chunk_4: ".",
      choice_options_1: ["all", "most", "many", "some", "few", "none"],
      choice_options_2: ["all", "most", "many", "some", "few", "none"],
      choice_options_3: ["right", "wrong"]
    },
    {
      QUD: '',
      bias: 0.2,
      row_number: 5,
      column_number: 12,
      condition: "high",
      question: "Describe these results of <strong>Green Valley</strong> so as to make it appear as if there is a <strong>high</strong> success rate without lying.",
      sentence_chunk_1: "In this exam",
      sentence_chunk_2: "of the students got",
      sentence_chunk_3: "of the questions",
      sentence_chunk_4: ".",
      choice_options_1: ["all", "most", "many", "some", "few", "none"],
      choice_options_2: ["all", "most", "many", "some", "few", "none"],
      choice_options_3: ["right", "wrong"]
      }
  ];

// the main trials are generated by calling the function create_trials with the corresponding arguments
// generate trials for flat bias (nr of trials, nr of rows, nr of columns, bias)

// main trials

const main_trials_data = _.shuffle(_.flatten([

    create_trials(1,5,12,0.2, "low"),
    create_trials(1,5,12,0.2, "high"),

    create_trials(1,5,12,0.3, "low"),
    create_trials(1,5,12,0.3, "high"),

    create_trials(1,5,12,0.4, "low"),
    create_trials(1,5,12,0.4, "high"),

    create_trials(1,5,12,0.5, "low"),
    create_trials(1,5,12,0.5, "high"),

    create_trials(1,5,12,0.6, "low"),
    create_trials(1,5,12,0.6, "high"),

    create_trials(1,5,12,0.7, "low"),
    create_trials(1,5,12,0.7, "high"),

    create_trials(1,5,12,0.8, "low"),
    create_trials(1,5,12,0.8, "high")

]));

console.log(main_trials_data);
